# -*- coding: utf-8 -*-
"""Linear Regression ML01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-6ZsxVdpIwKtf0WPAz6yXVK-zTpTuuj5
"""

#NEERAV DESAI 
#linear regression algo demonstration

import pandas as pd #loading the dataset
import numpy as np 
from sklearn import linear_model
import matplotlib.pyplot as plt #Visualising

from google.colab import files
uploaded = files.upload()

""" 
# **We will load the dataset**
"""

dataset = pd.read_csv('landpriceprediction.csv')
print (dataset.shape)
print(dataset.head(5))

"""# **Visualizing the dataset**"""

plt.xlabel('land')
plt.ylabel('price')
plt.scatter(dataset.land, dataset.price, color='black', marker='*')

"""#**Segregating the dataset**"""

land = dataset.drop('price', axis='columns')
land
#this is for land

price = dataset.price
price
#this is for price

"""# **Training Dataset using Linear regression**"""

model = linear_model.LinearRegression()
model.fit(land, price)

area_of_land = [[12000]]
Predictedmodelresult = model.predict(area_of_land)
print(Predictedmodelresult)

